# Generated by Django 4.0.1 on 2022-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_story_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
    ]
