version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - db_persistent:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: gunicorn tob.wsgi:application --bind 0.0.0.0:8008
    volumes:
      - ./code:/code
      - static:/static # static files
    ports:
      - "8000:8008"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PORT=8008
      - DEBUG=1
    depends_on:
      - db

volumes:
  db_persistent:
  static: