version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - db_persistent:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build: .
    command: gunicorn tob.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile -  --reload
    volumes:
      - ./code:/code
      - static:/static # static files
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_persistent:
  static: