# Generated by Django 4.0.1 on 2022-01-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='summary',
            field=models.CharField(max_length=2000),
        ),
    ]
