# Generated by Django 4.0.1 on 2022-02-02 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_alter_story_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'stories'},
        ),
    ]
