# Generated by Django 4.0.1 on 2022-02-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0004_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='text',
        ),
    ]
