# Generated by Django 4.0.1 on 2022-02-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0005_remove_story_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.FileField(default='', upload_to='story_text'),
            preserve_default=False,
        ),
    ]
