# Generated by Django 4.0.1 on 2022-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pub_date',
            field=models.DateField(max_length=100, verbose_name='date published'),
        ),
    ]
